"""Tests for timestamp field validation in Todo.from_dict() (Issue #2126).

These tests verify that:
1. Invalid types (int, list, dict) for created_at/updated_at are rejected
2. Valid string timestamps are accepted
3. Missing/null timestamps still work (default to current time)
"""

from __future__ import annotations

import pytest

from flywheel.todo import Todo


def test_todo_from_dict_rejects_list_created_at() -> None:
    """Todo.from_dict should reject list values for 'created_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'created_at'|'created_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "created_at": ["malicious"]})


def test_todo_from_dict_rejects_dict_created_at() -> None:
    """Todo.from_dict should reject dict values for 'created_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'created_at'|'created_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "created_at": {"key": "value"}})


def test_todo_from_dict_rejects_int_created_at() -> None:
    """Todo.from_dict should reject int values for 'created_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'created_at'|'created_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "created_at": 123456})


def test_todo_from_dict_rejects_list_updated_at() -> None:
    """Todo.from_dict should reject list values for 'updated_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'updated_at'|'updated_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "updated_at": ["malicious"]})


def test_todo_from_dict_rejects_dict_updated_at() -> None:
    """Todo.from_dict should reject dict values for 'updated_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'updated_at'|'updated_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "updated_at": {"key": "value"}})


def test_todo_from_dict_rejects_int_updated_at() -> None:
    """Todo.from_dict should reject int values for 'updated_at' field."""
    with pytest.raises(ValueError, match=r"invalid.*'updated_at'|'updated_at'.*string"):
        Todo.from_dict({"id": 1, "text": "task", "updated_at": 123456})


def test_todo_from_dict_accepts_valid_iso_timestamp() -> None:
    """Todo.from_dict should accept valid ISO string timestamps."""
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": "2024-01-01T00:00:00Z",
        "updated_at": "2024-01-02T00:00:00Z"
    })
    assert todo.created_at == "2024-01-01T00:00:00Z"
    assert todo.updated_at == "2024-01-02T00:00:00Z"


def test_todo_from_dict_accepts_missing_timestamps() -> None:
    """Todo.from_dict should accept missing/None timestamps and default correctly."""
    todo = Todo.from_dict({"id": 1, "text": "task"})
    # Timestamps should be auto-generated by __post_init__
    assert todo.created_at != ""
    assert todo.updated_at != ""
    assert todo.created_at == todo.updated_at


def test_todo_from_dict_accepts_null_timestamps() -> None:
    """Todo.from_dict should accept null timestamp values and default correctly."""
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": None,
        "updated_at": None
    })
    # Timestamps should be auto-generated by __post_init__
    assert todo.created_at != ""
    assert todo.updated_at != ""
    assert todo.created_at == todo.updated_at


def test_todo_from_dict_accepts_empty_string_timestamps() -> None:
    """Todo.from_dict should accept empty string timestamps and default correctly."""
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": "",
        "updated_at": ""
    })
    # Timestamps should be auto-generated by __post_init__
    assert todo.created_at != ""
    assert todo.updated_at != ""
    assert todo.created_at == todo.updated_at
