"""Test for Issue #294 - Windows DACL must be properly initialized.

This test ensures that the Windows DACL (Discretionary Access Control List)
is properly initialized and set on the security descriptor. Setting only the
owner is insufficient for security - the DACL must be properly configured.

Issue #294 was generated by an AI scanner noting that the comment on line 234
was truncated, but upon investigation, the actual DACL initialization code
(around lines 228-239) appears to be correct. This test verifies that the
DACL is indeed properly set.
"""

import pytest
import sys
from pathlib import Path
from unittest.mock import patch, MagicMock, call

# Skip this test on non-Windows platforms
pytestmark = pytest.mark.skipif(
    sys.platform != "win32",
    reason="Windows DACL test only applicable on Windows"
)


class TestWindowsDACLInitialization:
    """Test that Windows DACL is properly initialized (Issue #294)."""

    def test_dacl_is_properly_set_on_security_descriptor(self):
        """Test that DACL is created and set on the security descriptor.

        This test verifies that:
        1. A DACL object is created
        2. Access control entries are added to the DACL
        3. The DACL is set on the security descriptor with present=1

        If any of these steps are missing, Windows may use a default DACL
        that grants unrestricted access, which is a security vulnerability.
        """
        with patch('sys.modules', {'win32security': MagicMock(), 'win32con': MagicMock(), 'win32api': MagicMock()}):
            import win32security
            import win32con
            import win32api

            # Mock Windows constants
            win32con.FILE_LIST_DIRECTORY = 0x00000001
            win32con.FILE_ADD_FILE = 0x00000002
            win32con.FILE_READ_ATTRIBUTES = 0x00000080
            win32con.FILE_WRITE_ATTRIBUTES = 0x00000010
            win32con.SYNCHRONIZE = 0x00100000
            win32con.ACL_REVISION = 2
            win32security.ACL_REVISION = 2

            win32con.DELETE = 0x00010000
            win32con.FILE_ALL_ACCESS = 0x001F01FF

            # Mock SACL constants
            win32security.SE_DACL_PROTECTED = 1
            win32security.DACL_SECURITY_INFORMATION = 4
            win32security.PROTECTED_DACL_SECURITY_INFORMATION = 8
            win32security.OWNER_SECURITY_INFORMATION = 1
            win32security.SACL_SECURITY_INFORMATION = 16

            # Mock LookupAccountName
            mock_sid = MagicMock()
            win32security.LookupAccountName.return_value = (mock_sid, None, None)

            # Mock GetUserName and GetComputerName
            win32api.GetUserName.return_value = "testuser"
            win32api.GetComputerName.return_value = "TESTPC"
            win32api.GetUserNameEx.side_effect = Exception("Not in domain")

            # Mock SECURITY_DESCRIPTOR
            mock_sd = MagicMock()
            win32security.SECURITY_DESCRIPTOR.return_value = mock_sd

            # Mock ACL creation
            mock_dacl = MagicMock()
            mock_sacl = MagicMock()
            acl_call_count = [0]

            def mock_acl():
                acl_call_count[0] += 1
                return [mock_dacl, mock_sacl][acl_call_count[0] - 1]

            win32security.ACL.side_effect = mock_acl

            # Track SetSecurityDescriptorDacl calls
            dacl_calls = []

            def track_set_dacl(present, dacl, default):
                dacl_calls.append({
                    'present': present,
                    'dacl': dacl,
                    'default': default
                })

            mock_sd.SetSecurityDescriptorDacl = track_set_dacl
            mock_sd.SetSecurityDescriptorOwner = MagicMock()
            mock_sd.SetSecurityDescriptorSacl = MagicMock()
            mock_sd.SetSecurityDescriptorControl = MagicMock()

            # Import Storage after setting up mocks
            from flywheel.storage import Storage

            # Create a temporary storage
            import tempfile
            with tempfile.TemporaryDirectory() as tmpdir:
                storage_path = Path(tmpdir) / "test_todos.json"
                Storage(str(storage_path))

                # Verify DACL was created
                assert acl_call_count[0] >= 2, "ACL should be created for both DACL and SACL"

                # Verify DACL.AddAccessAllowedAce was called
                assert mock_dacl.AddAccessAllowedAce.called, \
                    "AddAccessAllowedAce should be called to add permissions to DACL"

                # Verify SetSecurityDescriptorDacl was called
                assert len(dacl_calls) > 0, "SetSecurityDescriptorDacl should be called"

                # Verify DACL was set with present=1 (DACL is present)
                assert dacl_calls[0]['present'] == 1, \
                    "DACL present flag should be 1 (indicating DACL is present)"

                # Verify DACL is not None (security vulnerability if None)
                assert dacl_calls[0]['dacl'] is not None, \
                    "DACL must not be None - this would allow unrestricted access"

                # Verify the DACL object passed is the same one we created
                assert dacl_calls[0]['dacl'] == mock_dacl, \
                    "The DACL object should be the one we created with AddAccessAllowedAce"

    def test_comment_is_not_truncated(self):
        """Verify the comment about minimal permissions is complete.

        Issue #294 was triggered by a truncated comment on line 234.
        This test verifies the comment has been fixed.
        """
        from flywheel.storage import Storage
        import inspect

        # Get the source code of the _secure_directory method
        source = inspect.getsource(Storage._secure_directory)

        # Check that the comment is not truncated
        # The old truncated comment was: "# Use minimal permissions instead of FILE_ALL_ACCESS (Issue #23"
        # The fixed comment should be: "# Use minimal permissions instead of FILE_ALL_ACCESS (Issue #239)"
        assert "# Issue #239" in source or "# Issue #23" not in source, \
            "Comment about minimal permissions should not be truncated"
