"""Tests for negative id validation in Todo.from_dict (Issue #4845).

These tests verify that:
1. Todo.from_dict rejects negative integers for 'id' field
2. Todo.from_dict accepts 0 and positive integers for 'id' field

Business context: Todo.id is generated by next_id starting from 1,
so valid ids should be non-negative integers.
"""

from __future__ import annotations

import pytest

from flywheel.todo import Todo


def test_todo_from_dict_rejects_negative_id() -> None:
    """Todo.from_dict should reject negative integers for 'id' field."""
    with pytest.raises(ValueError, match=r"invalid.*'id'|'id'.*non-negative|'id'.*positive|'id'.*negative"):
        Todo.from_dict({"id": -1, "text": "task"})


def test_todo_from_dict_rejects_large_negative_id() -> None:
    """Todo.from_dict should reject large negative integers for 'id' field."""
    with pytest.raises(ValueError, match=r"invalid.*'id'|'id'.*non-negative|'id'.*positive|'id'.*negative"):
        Todo.from_dict({"id": -999, "text": "task"})


def test_todo_from_dict_accepts_zero_id() -> None:
    """Todo.from_dict should accept 0 for 'id' field."""
    todo = Todo.from_dict({"id": 0, "text": "task"})
    assert todo.id == 0


def test_todo_from_dict_accepts_positive_id() -> None:
    """Todo.from_dict should accept positive integers for 'id' field."""
    todo = Todo.from_dict({"id": 1, "text": "task"})
    assert todo.id == 1


def test_todo_from_dict_accepts_large_positive_id() -> None:
    """Todo.from_dict should accept large positive integers for 'id' field."""
    todo = Todo.from_dict({"id": 999999, "text": "task"})
    assert todo.id == 999999
