"""Tests for from_dict timestamp preservation (Issue #4548).

These tests verify the behavior of from_dict when handling timestamp fields:
1. Explicit timestamp strings are preserved exactly
2. None values are treated as "generate new timestamp" (same as missing)
3. Missing fields trigger automatic timestamp generation
4. Empty strings trigger automatic timestamp generation

The key insight is that None and missing should be treated equivalently:
both result in empty string which triggers __post_init__ to generate timestamps.
"""

from __future__ import annotations

from flywheel.todo import Todo


def test_from_dict_preserves_explicit_timestamps() -> None:
    """from_dict should preserve explicitly provided timestamp strings."""
    original_created = "2024-01-15T10:30:00+00:00"
    original_updated = "2024-01-16T14:45:00+00:00"

    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": original_created,
        "updated_at": original_updated,
    })

    assert todo.created_at == original_created
    assert todo.updated_at == original_updated


def test_from_dict_none_timestamps_generate_new() -> None:
    """from_dict should treat None timestamps as 'generate new timestamp'.

    Issue #4548: str(data.get('created_at') or '') correctly handles None by
    converting to empty string, which triggers __post_init__ to generate timestamps.
    This is intentional behavior - None means "no timestamp provided, generate one".
    """
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": None,
        "updated_at": None,
    })

    # __post_init__ should generate timestamps since None is treated as "not provided"
    assert todo.created_at != ""
    assert todo.updated_at != ""
    assert todo.created_at == todo.updated_at


def test_from_dict_missing_timestamps_generates_new() -> None:
    """from_dict should generate timestamps when fields are missing entirely."""
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
    })

    # __post_init__ should generate timestamps since fields are missing
    assert todo.created_at != ""
    assert todo.updated_at != ""
    assert todo.created_at == todo.updated_at


def test_from_dict_empty_string_timestamps_generate_new() -> None:
    """from_dict should treat empty string timestamps as 'generate new timestamp'."""
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": "",
        "updated_at": "",
    })

    # Empty strings trigger __post_init__ to generate new timestamps
    assert todo.created_at != ""
    assert todo.updated_at != ""


def test_from_dict_only_created_at_provided() -> None:
    """from_dict should handle case where only created_at is provided."""
    original_created = "2024-01-15T10:30:00+00:00"

    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": original_created,
    })

    assert todo.created_at == original_created
    # updated_at should be set to created_at by __post_init__
    assert todo.updated_at == original_created


def test_from_dict_only_updated_at_provided() -> None:
    """from_dict should handle case where only updated_at is provided."""
    original_updated = "2024-01-16T14:45:00+00:00"

    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "updated_at": original_updated,
    })

    # created_at should be generated by __post_init__
    assert todo.created_at != ""
    # updated_at should be preserved
    assert todo.updated_at == original_updated
