"""Regression test for issue #6604: Race condition in ID generation.

Tests that concurrent add() operations do not produce duplicate IDs.
The bug occurs because next_id() computes max+1 without synchronization,
leading to a TOCTOU (Time-of-check to time-of-use) race condition.
"""

from __future__ import annotations

import multiprocessing

from flywheel.cli import TodoApp
from flywheel.storage import TodoStorage


def add_todos_worker(db_path: str, worker_id: int, num_todos: int, result_queue: multiprocessing.Queue) -> None:
    """Worker function that adds multiple todos and returns the IDs generated."""
    try:
        app = TodoApp(db_path)
        ids_generated = []
        for i in range(num_todos):
            todo = app.add(f"worker-{worker_id}-todo-{i}")
            ids_generated.append(todo.id)
        result_queue.put(("success", worker_id, ids_generated))
    except Exception as e:
        result_queue.put(("error", worker_id, str(e)))


def test_concurrent_add_produces_unique_ids(tmp_path) -> None:
    """Regression test for issue #6604: Race condition in ID generation.

    Two concurrent add() operations should not produce todos with the same ID.
    This test spawns multiple processes that each add todos to the same database
    concurrently and verifies that all resulting IDs are unique.
    """
    db_path = str(tmp_path / "concurrent.json")

    # Run multiple workers concurrently, each adding multiple todos
    num_workers = 4
    todos_per_worker = 25

    processes = []
    result_queue = multiprocessing.Queue()

    for i in range(num_workers):
        p = multiprocessing.Process(
            target=add_todos_worker,
            args=(db_path, i, todos_per_worker, result_queue)
        )
        processes.append(p)
        p.start()

    # Wait for all processes to complete
    for p in processes:
        p.join(timeout=30)

    # Collect results
    results = []
    while not result_queue.empty():
        results.append(result_queue.get())

    # Check for errors
    errors = [r for r in results if r[0] == "error"]
    assert len(errors) == 0, f"Workers encountered errors: {errors}"

    # Collect all IDs generated by all workers
    all_ids = []
    successes = [r for r in results if r[0] == "success"]
    for success in successes:
        _, _worker_id, ids_generated = success
        all_ids.extend(ids_generated)

    # Verify all IDs are unique - this is the core assertion for issue #6604
    unique_ids = set(all_ids)
    assert len(unique_ids) == len(all_ids), (
        f"Duplicate IDs detected! Generated {len(all_ids)} IDs but only "
        f"{len(unique_ids)} are unique. Duplicates: "
        f"{[i for i in all_ids if all_ids.count(i) > 1]}"
    )

    # Verify the storage has all todos with unique IDs
    storage = TodoStorage(db_path)
    final_todos = storage.load()

    # All todos should have unique IDs
    final_ids = [todo.id for todo in final_todos]
    unique_final_ids = set(final_ids)
    assert len(unique_final_ids) == len(final_ids), (
        f"Duplicate IDs in final storage! Found {len(final_ids)} todos but only "
        f"{len(unique_final_ids)} unique IDs"
    )


def test_concurrent_add_with_existing_todos(tmp_path) -> None:
    """Test that concurrent adds work correctly when there are existing todos."""
    db_path = str(tmp_path / "concurrent_existing.json")

    # Pre-populate with some existing todos
    app = TodoApp(db_path)
    for i in range(1, 6):
        app.add(f"existing-{i}")

    initial_max_id = max(todo.id for todo in app.list())

    # Run concurrent adds
    num_workers = 3
    todos_per_worker = 10

    processes = []
    result_queue = multiprocessing.Queue()

    for i in range(num_workers):
        p = multiprocessing.Process(
            target=add_todos_worker,
            args=(db_path, i + 100, todos_per_worker, result_queue)
        )
        processes.append(p)
        p.start()

    for p in processes:
        p.join(timeout=30)

    # Collect all IDs
    all_ids = []
    while not result_queue.empty():
        result = result_queue.get()
        if result[0] == "success":
            all_ids.extend(result[2])

    # All newly generated IDs should be unique
    unique_ids = set(all_ids)
    assert len(unique_ids) == len(all_ids), (
        f"Duplicate IDs in concurrent adds! "
        f"Duplicates: {[i for i in all_ids if all_ids.count(i) > 1]}"
    )

    # All new IDs should be greater than the initial max ID
    for new_id in all_ids:
        assert new_id > initial_max_id, (
            f"New ID {new_id} should be greater than initial max ID {initial_max_id}"
        )


def test_sequential_add_produces_unique_ids(tmp_path) -> None:
    """Baseline test: sequential adds should always produce unique IDs."""
    db_path = str(tmp_path / "sequential.json")
    app = TodoApp(db_path)

    ids = []
    for i in range(100):
        todo = app.add(f"todo-{i}")
        ids.append(todo.id)

    # All IDs should be unique
    assert len(set(ids)) == len(ids), "Sequential adds produced duplicate IDs"

    # IDs should be sequential starting from 1
    expected_ids = list(range(1, 101))
    assert ids == expected_ids, f"Expected sequential IDs {expected_ids}, got {ids}"
