"""Tests for from_dict timestamp handling (Issue #4548).

These tests verify that:
1. from_dict preserves explicit timestamp values (including None -> empty string)
2. from_dict does not regenerate timestamps when values are explicitly None
3. The current behavior is documented through tests
"""

from __future__ import annotations

from flywheel.todo import Todo


def test_from_dict_preserves_explicit_created_at_none() -> None:
    """When created_at is explicitly None, __post_init__ generates new timestamp.

    This tests the current documented behavior: passing None for created_at
    results in a new timestamp being generated by __post_init__, same as
    passing an empty string or omitting the field.
    """
    todo = Todo.from_dict({"id": 1, "text": "task", "created_at": None})
    # When created_at is None, str(None or "") = "", triggers __post_init__
    # to generate a new timestamp
    assert todo.created_at != ""
    assert todo.created_at != "None"  # Should not be string "None"


def test_from_dict_preserves_explicit_updated_at_none() -> None:
    """When updated_at is explicitly None, __post_init__ generates new timestamp.

    This tests the current documented behavior: passing None for updated_at
    results in a new timestamp being generated by __post_init__, same as
    passing an empty string or omitting the field.
    """
    todo = Todo.from_dict({"id": 1, "text": "task", "updated_at": None})
    # When updated_at is None, str(None or "") = "", triggers __post_init__
    # to generate a new timestamp (same as created_at)
    assert todo.updated_at != ""
    assert todo.updated_at != "None"  # Should not be string "None"


def test_from_dict_preserves_explicit_timestamps() -> None:
    """from_dict should preserve explicit timestamp strings."""
    explicit_time = "2024-01-01T00:00:00+00:00"
    todo = Todo.from_dict({
        "id": 1,
        "text": "task",
        "created_at": explicit_time,
        "updated_at": explicit_time,
    })
    assert todo.created_at == explicit_time
    assert todo.updated_at == explicit_time


def test_from_dict_generates_timestamps_when_missing() -> None:
    """When timestamp fields are missing, __post_init__ generates them."""
    todo = Todo.from_dict({"id": 1, "text": "task"})
    assert todo.created_at != ""
    assert todo.updated_at != ""


def test_from_dict_generates_timestamps_when_empty_string() -> None:
    """When timestamp fields are empty strings, __post_init__ generates them."""
    todo = Todo.from_dict({"id": 1, "text": "task", "created_at": "", "updated_at": ""})
    assert todo.created_at != ""
    assert todo.updated_at != ""


def test_from_dict_timestamp_behavior_is_consistent() -> None:
    """Verify that None, empty string, and missing all behave consistently.

    All three cases should result in __post_init__ generating a new timestamp,
    not preserving any "None" or empty value.
    """
    import time

    # Test with explicit None
    todo_none = Todo.from_dict({"id": 1, "text": "task", "created_at": None})
    time.sleep(0.01)  # Small delay to ensure different timestamp
    # Test with empty string
    todo_empty = Todo.from_dict({"id": 2, "text": "task", "created_at": ""})
    time.sleep(0.01)
    # Test with missing field
    todo_missing = Todo.from_dict({"id": 3, "text": "task"})

    # All should have non-empty timestamps
    assert todo_none.created_at != ""
    assert todo_empty.created_at != ""
    assert todo_missing.created_at != ""

    # None should NOT be stringified to "None"
    assert todo_none.created_at != "None"
